#!/bin/bash
python main.py \
--dataset=spatial-maps \
--data_dir=/home/data/world-cities/ \
--log_dir=/home/workspace/citygan/ \
--num_gpu=4 \
--comment="using lum channel, ELU->tanh in final layer of G/D" \
--use_tensorboard=True \
--load_attributes="region,profiles" \
--src_names="bldg,pop,lum,water,bounds" \
--lr=0.0001 \
--batch_size=32 \
--input_scale_size=64 \
--use_channels="1" \
--normalize_channels=False \
--normalize=True \
--rotate_angle=0 \
--flips=True \
--take_log=True \
--save_step=2000 \
--lambda_k=0.001 \
--gamma=0.5 \
--conv_hidden_num=128 \
--z_num=128 